# Generated by Django 4.1.7 on 2023-04-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Costumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='publish', max_length=250, unique_for_date='publish'),
        ),
    ]
