# Generated by Django 4.1.7 on 2023-05-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='kin_phone',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='next_of_kin',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
