# Generated by Django 4.1.7 on 2023-05-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_passenger_email_passenger_kin_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
